version: '3.7'

services:
  vsftpd:
    image: fauria/vsftpd
    deploy:
      replicas: 1
    ports:
      - 20-21:20-21
      - 21100-21110:21100-21110
    volumes:
      - /mnt/md0/videos:/home/vsftpd/alex/videos
    environment:
      FTP_USER: alex
      PASV_ADDRESS: meadowbrook.taxiera.link
      PASV_MIN_PORT: 21100
      PASV_MAX_PORT: 21110
      PASV_ADDR_RESOLVE: 'YES'
      REVERSE_LOOKUP_ENABLE: 'NO'
  samba:
    image: ghcr.io/servercontainers/samba
    hostname: samba
    deploy:
      replicas: 1
    environment:
      SAMBA_CONF_MAP_TO_GUEST: never
      SAMBA_GLOBAL_CONFIG_unix_SPACE_extensions: 'no'

      ACCOUNT_alex: 'alex:1010:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:EFB37715BBBCE9F7422983705F5B37F3:[U          ]:LCT-629CBF57:'
      ACCOUNT_debbie: 'debbie:1011:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:0057729555F7F629DAD83FB54EFC5862:[U          ]:LCT-619013A2:'
      ACCOUNT_fig: 'fig:1012:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:33119A56ED8795BDE29B397FE53E128D:[U          ]:LCT-619013C6:'

      GROUP_samba: 1050
      GROUPS_alex: alex,samba
      GROUPS_debbie: samba
      GROUPS_fig: samba

      SAMBA_VOLUME_CONFIG_ADMIN: '[Admin]; path=/mnt/md0; read only = no; valid users = alex, debbie; admin users = alex, debbie;'
      SAMBA_VOLUME_CONFIG_PUBLIC: '[Public]; path=/mnt/md0/samba/public; read only = yes; valid users = debbie, fig, alex; admin users = alex; follow symlinks = yes; wide links = yes'
    ports:
      - target: 137
        published: 137
        mode: host
        protocol: udp
      - target: 138
        published: 138
        mode: host
        protocol: udp
      - target: 139
        published: 139
        mode: host
      - target: 445
        published: 445
        mode: host
    volumes:
      - /mnt/md0:/mnt/md0
      - /mnt/md0/samba/public:/mnt/md0/samba/public
    cap_add:
      - CAP_NET_ADMIN
