version: '3.9'

services:
  main:
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - 8211:8211/udp
      - 25571:25575
    environment:
      - ALWAYS_UPDATE_ON_START=false
      - GAME_PORT=8211
      - MAX_PLAYERS=16
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - PUBLIC_IP=meadowbrook.taxiera.link
      - PUBLIC_PORT=8211
    volumes:
      - /mnt/disk1/palworld/main:/palworld

  glizzy:
    image: jammsen/palworld-dedicated-server:latest
    restart: unless-stopped
    ports:
      - 8222:8211/udp
      - 25581:25575
    environment:
      - ALWAYS_UPDATE_ON_START=false
      - GAME_PORT=8211
      - MAX_PLAYERS=16
      - MULTITHREAD_ENABLED=true
      - COMMUNITY_SERVER=false
      - PUBLIC_IP=meadowbrook.taxiera.link
      - PUBLIC_PORT=8222
    volumes:
      - /mnt/disk1/palworld/glizzy:/palworld
