version: '3.7'

services:
  smbd:
    image: servercontainers/samba
    hostname: samba
    deploy:
      replicas: 1
    environment:
      SAMBA_CONF_MAP_TO_GUEST: never
      SAMBA_GLOBAL_CONFIG_unix_SPACE_extensions: 'no'

      ACCOUNT_alex: 'alex:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:EFB37715BBBCE9F7422983705F5B37F3:[U          ]:LCT-629CBF57:'
      ACCOUNT_fig: 'fig:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:33119A56ED8795BDE29B397FE53E128D:[U          ]:LCT-619013C6:'
      ACCOUNT_debbie: 'debbie:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:0057729555F7F629DAD83FB54EFC5862:[U          ]:LCT-619013A2:'
      GROUPS_alex: alex

      SAMBA_VOLUME_CONFIG_ADMIN: '[Admin]; path=/mnt/md0; browseable = yes; read only = no; valid users = alex'
      SAMBA_VOLUME_CONFIG_PUBLIC: '[Public]; path=/mnt/md0/samba/public; browseable = yes; read only = no; valid users = example, debbie, fig, alex; admin users = alex; follow symlinks = yes; wide links = yes'
    ports:
      - "139:139/tcp"
      - "445:445/tcp"
    volumes:
      - /mnt/md0:/mnt/md0
      - /mnt/md0/samba/public:/mnt/md0/samba/public
    cap_add:
      - CAP_NET_ADMIN
