#!/bin/bash
export EXTERNAL_IP=$(hostname -I | cut -d " " -f 1)
sudo docker image prune -a -f
sudo docker stack deploy --prune --with-registry-auth --resolve-image=always -c ${2:-docker-compose.yml} ${1:-stack}
