version: '3.7'

x-common-variables: &common
  NODE_ENV: production
  DB_HOST: db
  DB_CLIENT: pg

networks:
  postgres_backend_network:

secrets:
  ADMIN_DB_USER:
    external: true
  ADMIN_DB_PASS:
    external: true
  IMGUR_CLIENT_ID:
    external: true
  TUX_TOKEN:
    external: true
  TUX_DB_NAME:
    external: true
  TUX_DB_USER:
    external: true
  TUX_DB_PASS:
    external: true
  TAG_TOKEN:
    external: true
  TAG_DB_NAME:
    external: true
  TAG_DB_USER:
    external: true
  TAG_DB_PASS:
    external: true
  ELI_TOKEN:
    external: true
  READONLY_USER:
    external: true
  READONLY_PASS:
    external: true
  AVC_CLIENT_ID:
    external: true
  AVC_TOKEN:
    external: true
  CAALYX_ID:
    external: true

services:
  tux:
    image: alextaxiera/bots:tuxedoman-1
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    secrets:
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
      -
        source: TUX_DB_NAME
        target: DB_NAME
      -
        source: TUX_DB_USER
        target: DB_USER
      -
        source: TUX_DB_PASS
        target: DB_PASS
      -
        source: TUX_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common

  tag:
    image: alextaxiera/bots:tag-19
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    secrets:
      - IMGUR_CLIENT_ID
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
      -
        source: TAG_DB_NAME
        target: DB_NAME
      -
        source: TAG_DB_USER
        target: DB_USER
      -
        source: TAG_DB_PASS
        target: DB_PASS
      -
        source: TAG_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common

  eli:
    image: alextaxiera/bots:eli-12
    deploy:
      replicas: 1
    secrets:
      -
        source: ELI_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common

  db:
    image: alextaxiera/bots:pg-7
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_backend_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      -
        type: bind
        source: ~/docker/volumes/postgres
        target: /var/lib/postgresql/data
    secrets:
      - TUX_DB_NAME
      - TUX_DB_USER
      - TUX_DB_PASS
      - TAG_DB_NAME
      - TAG_DB_USER
      - TAG_DB_PASS
      - READONLY_USER
      - READONLY_PASS
      -
        source: ADMIN_DB_USER
        target: ADMIN_USER
      -
        source: ADMIN_DB_PASS
        target: ADMIN_PASS
    environment:
      POSTGRES_USER_FILE: /run/secrets/ADMIN_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/ADMIN_PASS

  avc:
    image: vinanrra/auto-voice-channels
    container_name: AutoVoiceChannels
    secrets:
      -
        source: AVC_CLIENT_ID
        target: CLIENT_ID
      -
        source: AVC_TOKEN
        target: TOKEN
      -
        source: CAALYX_ID
        target: ADMIN_ID
    environment:
      TZ: America/New_York
    volumes:
      - ~/docker/volumes/avc:/AutoVoiceChannels/guilds:Z
