version: '3.7'

x-common-variables: &common
  NODE_ENV: production
  DB_HOST: db
  DB_CLIENT: pg

networks:
  postgres_backend_network:

secrets:
  ADMIN_DB_USER:
    external: true
  ADMIN_DB_PASS:
    external: true
  IMGUR_CLIENT_ID:
    external: true
  TUX_TOKEN:
    external: true
  PETER_TOKEN:
    external: true
  TAGGER_TOKEN:
    external: true
  ELI_TOKEN:
    external: true

services:
  tux:
    image: alextaxiera/bots:tuxedoman-18
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    secrets:
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
      -
        source: TUX_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common
      DB_NAME: tuxedoman
      DB_USER: tux
      DB_PASS: tuxedomask

  tag:
    image: alextaxiera/bots:tag-10
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    secrets:
      - IMGUR_CLIENT_ID
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
      -
        source: TAGGER_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common
      DB_NAME: tagger
      DB_USER: tag
      DB_PASS: tagbot

  eli:
    image: alextaxiera/bots:eli-7
    deploy:
      replicas: 1
    secrets:
      -
        source: ELI_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common

  peter:
    image: alextaxiera/bots:peter-dev-13
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    secrets:
      - ADMIN_DB_USER
      - ADMIN_DB_PASS
      -
        source: PETER_TOKEN
        target: DISCORD_TOKEN
    environment:
      <<: *common
      DB_NAME: peter
      DB_USER: pete
      DB_PASS: pattar

  db:
    image: alextaxiera/bots:pg-2
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_backend_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      -
        type: bind
        source: ~/docker/volumes/postgres
        target: /var/lib/postgresql/data
