version: '3.7'

services:
  tux:
    image: alextaxiera/bots:tuxedoman-master-9
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    environment:
      NODE_ENV: 'production'
      TUX_DB_CLIENT: 'pg'
      TUX_DISCORD_TOKEN: 'NDQxMzY2NjI4ODM2NDQyMTIy.XhpRFQ.oUqfa4bKNXR3RQRMGDOubMVb8fc'
      TUX_DB_NAME: 'tuxedoman'
      TUX_DB_USER: 'tux'
      TUX_DB_PASS: 'tuxedomask'
      TUX_DB_HOST: 'db'

  tag:
    image: alextaxiera/bots:tag-dev-2
    deploy:
      replicas: 1
    depends_on:
      - db
    networks:
      - postgres_backend_network
    environment:
      NODE_ENV: 'production'
      TAG_DB_CLIENT: 'pg'
      TAG_DISCORD_TOKEN: 'NTIwNzgzNDQxODY4ODgxOTIw.Duy5jw._mvXvfSxyglMSmjJssRUQXwRK6g'
      TAG_IMGUR_CLIENT_ID: '41b60de5c6bfd49'
      TAG_DB_NAME: 'tagger'
      TAG_DB_USER: 'tag'
      TAG_DB_PASS: 'tagbot'
      TAG_DB_HOST: 'db'

  eli:
    image: alextaxiera/bots:eli-master-3
    deploy:
      replicas: 1
    environment:
      NODE_ENV: 'production'
      GB_TOKEN: 'NDM2MjI2NDE1ODM5Njc0MzY4.Xi5vYA.M-OfRQmeuV0k-My76BA7lgdJ6bw'

  peter:
    image: alextaxiera/bots:peter-dev-1
    deploy:
      replicas: 1
    environment:
      NODE_ENV: 'production'
      STREAM_DISCORD_TOKEN: 'NDQxMzY4NjEyOTE4Mzk0ODkw.Dskuqg.WsSG3DWkg6RNK1SyEekK-D68zaU'
      STREAM_DB_CLIENT: 'pg'
      STREAM_DB_NAME: 'peter'
      STREAM_DB_USER: 'pete'
      STREAM_DB_PASS: 'pattar'
      STREAM_DB_HOST: 'db'

  db:
    image: alextaxiera/bots:pg-2
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_backend_network
    environment:
      POSTGRES_USER: 'my_admin'
      POSTGRES_PASSWORD: 'esp10n4g31sb4d'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ~/docker/volumes/postgres
        target: /var/lib/postgresql/data

networks:
  postgres_backend_network:
