version: '3.7'

services:
  tux:
    image: alextaxiera/bots:tuxedoman-master-9
    secrets:
      - postgres_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - db
    networks:
      - postgres_backend_network
    environment:
      NODE_ENV: 'production'
      TUX_DB_CLIENT: 'pg'
      TUX_DISCORD_TOKEN: 'NDQxMzY2NjI4ODM2NDQyMTIy.XhpRFQ.oUqfa4bKNXR3RQRMGDOubMVb8fc'
      TUX_DB_NAME: 'tuxedoman'
      TUX_DB_USER: 'tux'
      TUX_DB_PASS: 'tuxedomask'
      TUX_DB_HOST: 'db'

  tag:
    image: alextaxiera/bots:tag-dev-2
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    depends_on:
      - db
    networks:
      - postgres_backend_network
    environment:
      NODE_ENV: 'production'
      TAG_DB_CLIENT: 'pg'
      TAG_DISCORD_TOKEN: 'NTIwNzgzNDQxODY4ODgxOTIw.Duy5jw._mvXvfSxyglMSmjJssRUQXwRK6g'
      TAG_IMGUR_CLIENT_ID: '41b60de5c6bfd49'
      TAG_DB_NAME: 'tagger'
      TAG_DB_USER: 'tag'
      TAG_DB_PASS: 'tagbot'
      TAG_DB_HOST: 'db'

  eli:
    image: alextaxiera/bots:eli-master-3
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    environment:
      NODE_ENV: 'production'
      GB_TOKEN: 'NDM2MjI2NDE1ODM5Njc0MzY4.Xi5vYA.M-OfRQmeuV0k-My76BA7lgdJ6bw'

  db:
    image: my-pg:latest
    secrets:
      - postgres_password
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_backend_network
    environment:
      POSTGRES_USER: 'my_admin'
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - type: bind
        source: ~/docker/volumes/postgres
        target: /var/lib/postgresql/data

networks:
  postgres_backend_network:

secrets:
  postgres_password:
    external: true
