volumes:
  storage:
    external: true 

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: America/New_York
      PLEX_UID: 1000
      PLEX_GID: 1000
      #PLEX_CLAIM: <claimToken>
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      - storage:/data:ro
      -
        type: tmpfs
        target: /transcode
        tmpfs:
          size: "5368709120"
