version: '3.7'

services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    network_mode: host
    privileged: true
    restart: always
    hostname: RHEA
    environment:
      TZ: America/New_York
      #PLEX_CLAIM: <claimToken>
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      - /merge/disk1:/data
      -
        type: tmpfs
        target: /transcode
        tmpfs:
          size: 50000
