volumes:
  storage:
    external: true 

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: America/New_York
      PLEX_UID: 1000
      PLEX_GID: 1000
      #PLEX_CLAIM: <claimToken>
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      - storage:/data:ro
      -
        type: tmpfs
        target: /transcode
        tmpfs:
          size: "5368709120"

  photostructure:
    image: photostructure/server
    restart: unless-stopped

    # PhotoStructure needs some time to close the database cleanly.
    # (It should normally only take seconds, but 2m accounts for
    # a spun-down, remote, old HDD hosting a very large library):
    stop_grace_period: 2m

    ports:
      - 1787:1787/tcp

    environment:
      # PhotoStructure has _tons_ of settings. See
      # <https://photostructure.com/faq/environment-variables/>

      # If PhotoStructure is refusing to spin up, uncomment these lines to see what's going on:
      #PS_LOG_LEVEL: info
      #PS_LOG_STDOUT: true
      TZ: America/New_York
      PUID: 1000
      PGID: 1000

    volumes:
      # /ps/library is where your PhotoStructure Library will be stored.
      # It must be readable, writable, and have sufficient free space.
      # If it is a remote volume, uncomment the PS_FORCE_LOCAL_DB_REPLICA
      # environment line below.

      - /home/alex/docker/volumes/photostructure/library:/ps/library
      #type: volume
      #   source: storage
      #   target: /ps/library
      #   volume:
      #     subpath: photostructure

      # NOTE: if /ps/library is a fast local disk, you can delete 
      # the other /ps/... bind mounts below.
      
      # /ps/tmp must be fast, local disk with many gigabytes free.
      # PhotoStructure will use this directory for file caching
      # and for storing a temporary database replica when your
      # library is on a remote volume.

      # - type: bind
      #   source: "${HOME}/.cache/photostructure"
      #   target: /ps/tmp

      # - type: bind
      #   source: "${HOME}/.config/PhotoStructure-docker"
      #   target: /ps/config

      # - type: bind
      #   source: "${HOME}/.config/PhotoStructure/logs"
      #   target: /ps/logs

      - type: volume
        source: storage
        target: /var/debbie
        volume:
          subpath: photos/debbie

      # Here's an example directory to scan:
      # - type: bind
      #   source: /home/jamie/Pictures
      #   target: /var/home-jamie-pictures

  ersatstv:
    image: jasongdove/ersatztv
    restart: unless-stopped
    ports:
      - 8409:8409
    environment:
      TZ: America/New_York
    volumes:
      - /home/alex/docker/volumes/ersatstv/config:/root/.local/share/ersatstv
      - storage:/data:ro
  
  romm:
    image: rommapp/romm:latest
    restart: unless-stopped
    environment:
      DB_HOST: media-romm-db-1
      DB_NAME: romm # Should match MARIADB_DATABASE in mariadb
      DB_USER: ${ROMM_DB_USER?error}
      DB_PASSWD: ${ROMM_DB_PASSWORD?error}
      IGDB_CLIENT_ID: ${IGDB_CLIENT_ID?error}
      IGDB_CLIENT_SECRET: ${IGDB_CLIENT_SECRET?error}
      MOBYGAMES_API_KEY: ${MOBYGAMES_API_KEY?error}
      ROMM_AUTH_USERNAME: ${ROMM_AUTH_USERNAME?error}
      ROMM_AUTH_PASSWORD: ${ROMM_AUTH_PASSWORD?error}
      ROMM_AUTH_SECRET_KEY: ${ROMM_AUTH_SECRET_KEY?error}
    volumes:
      - /home/alex/docker/volumes/romm/resources:/romm/resources # Resources fetched from IGDB (covers, screenshots, etc.)
      - /home/alex/docker/volumes/romm/redis-data:/redis-data # Cached data for background tasks
      - type: volume
        source: storage
        target: /romm/assets
        volume:
          subpath: romm/assets
      - type: volume
        source: storage
        target: /romm/config
        volume:
          subpath: romm/config
      # mapping to roms folders
      - type: volume
        source: storage
        target: /romm/library/roms/gc
        volume:
          subpath: games/ROMs/1G1R - Redump - Nintendo - GameCube
      - type: volume
        source: storage
        target: /romm/library/roms/dc
        volume:
          subpath: games/ROMs/1G1R - Redump - Sega - Dreamcast
      - type: volume
        source: storage
        target: /romm/library/roms/saturn
        volume:
          subpath: games/ROMs/1G1R - Redump - Sega - Saturn
      - type: volume
        source: storage
        target: /romm/library/roms/ps
        volume:
          subpath: games/ROMs/1G1R - Redump - Sony - PlayStation
      - type: volume
        source: storage
        target: /romm/library/roms/ps
        volume:
          subpath: games/ROMs/1G1R - Redump - Sony - PlayStation (Part 2)
      - type: volume
        source: storage
        target: /romm/library/roms/segacd
        volume:
          subpath: games/ROMs/1G1R - Redump+No-Intro - Sega - CD+32X/CD
      - type: volume
        source: storage
        target: /romm/library/roms/sega32
        volume:
          subpath: games/ROMs/1G1R - Redump+No-Intro - Sega - CD+32X/32X
      - type: volume
        source: storage
        target: /romm/library/roms/gb
        volume:
          subpath: games/ROMs/GB
      - type: volume
        source: storage
        target: /romm/library/roms/gba
        volume:
          subpath: games/ROMs/GBA
      - type: volume
        source: storage
        target: /romm/library/roms/gbc
        volume:
          subpath: games/ROMs/GBC
      - type: volume
        source: storage
        target: /romm/library/roms/n64
        volume:
          subpath: games/ROMs/N64
    ports:
      - 8089:8080
    depends_on:
      - romm-db

  romm-db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: romm
      MARIADB_ROOT_PASSWORD: ${ROMM_DB_ROOT_PASSWORD?error}
      MARIADB_USER: ${ROMM_DB_USER?error}
      MARIADB_PASSWORD: ${ROMM_DB_PASSWORD?error}
    volumes:
      - /home/alex/docker/volumes/romm/mariadb-data:/var/lib/mysql
