version: '3.7'

networks:
  nginx-proxy:
    external: true

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: America/New_York
      PLEX_UID: 1000
      PLEX_GID: 1000
      #PLEX_CLAIM: <claimToken>
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      -
        type: tmpfs
        target: /transcode
        tmpfs:
          size: "5368709120"
      - /mnt/disk1:/data
  emby:
    image: emby/embyserver
    runtime: nvidia # Expose NVIDIA GPUs
    networks:
      - nginx-proxy
    environment:
      UID: 1000 # The UID to run emby as (default: 2)
      GID: 1000 # The GID to run emby as (default 2)
      GIDLIST: 1000 # A comma-separated list of additional GIDs to run emby as (default: 2)
      LETSENCRYPT_HOST: media.taxiera.link
      LETSENCRYPT_EMAIL: alex.taxiera@gmail.com
      VIRTUAL_HOST: media.taxiera.link
      VIRTUAL_PORT: 8096
    volumes:
      - /home/alex/docker/volumes/emby/config:/config # Configuration directory
      - /mnt/disk1/videos/shows:/mnt/share1 # Media directory
      - /mnt/disk1/videos/movies:/mnt/share2 # Media directory
      - /mnt/disk1/videos/anime:/mnt/share3 # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
      - /dev/vchiq:/dev/vchiq # MMAL/OMX on Raspberry Pi
    restart: unless-stopped
