version: '3.7'

services:
  plex:
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - "32400"
      - "8324"
      - "32469"
      - "1900/udp"
      - "32410/udp"
      - "32412/udp"
      - "32413/udp"
      - "32414/udp"
    environment:
      TZ: America/New_York
      PLEX_UID: 1000
      PLEX_GID: 1000
      #PLEX_CLAIM: <claimToken>
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      -
        type: tmpfs
        target: /transcode
        tmpfs:
          size: "5368709120"
      - /mnt/disk1:/data
