version: '3.7'

services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    privileged: true
    restart: always
    hostname: HESTIA
    environment:
      VERSION: public
      TZ: America/New_York
      #PLEX_CLAIM: <claimToken>
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      - /home/alex/docker/volumes/plex/transcode:/transcode
      - /media/folso:/data
