version: '3.7'

services:
  plex:
    image: plexinc/pms-docker
    environment:
      - TZ=America/New_York
      - ADVERTISE_IP=http://10.4.20.220:32400/
      # - PLEX_CLAIM=<claimToken>
    hostname: HESTIA
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    devices:
      - /dev/dri/:/dev/dri/
    volumes:
      - /home/alex/docker/volumes/plex/config:/config
      - /home/alex/docker/volumes/plex/transcode:/transcode
      - /media/folso:/data
