networks:
  cloudflare:
    external: true

volumes:
  storage:
    external: true 

services:
  transmission:
    restart: unless-stopped
    image: ghcr.io/linuxserver/transmission
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
    volumes:
      -
        type: volume
        source: storage
        target: /downloads
        volume:
          subpath: torrents
      - storage:/media
      - /home/alex/docker/volumes/transmission/config:/config
      - /home/alex/docker/volumes/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
  samba:
    restart: unless-stopped
    image: ghcr.io/servercontainers/samba
    environment:
      SAMBA_CONF_MAP_TO_GUEST: never
      SAMBA_GLOBAL_CONFIG_unix_SPACE_extensions: 'no'
      GROUP_samba: 1050

      ACCOUNT_alex: 'alex:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:BFE9F9ECB595C335FAC0B0186614E341:[U          ]:LCT-66C63102:'
      GROUPS_alex: alex,samba

      ACCOUNT_debbie: 'debbie:1011:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:0057729555F7F629DAD83FB54EFC5862:[U          ]:LCT-619013A2:'
      GROUPS_debbie: samba

      ACCOUNT_fig: 'fig:1012:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:33119A56ED8795BDE29B397FE53E128D:[U          ]:LCT-619013C6:'
      GROUPS_fig: samba


      SAMBA_VOLUME_CONFIG_ADMIN: '[Admin]; path=/media/storage; read only = no; valid users = alex, debbie; admin users = alex; follow symlinks = yes; wide links = yes'

      SAMBA_VOLUME_CONFIG_GAMES: '[Games]; path=/media/games; read only = yes; valid users = debbie, fig, alex; admin users = alex'
      SAMBA_VOLUME_CONFIG_VIDEOS: '[Videos]; path=/media/videos; read only = yes; valid users = debbie, fig, alex; admin users = alex'
      SAMBA_VOLUME_CONFIG_SOFTWARE: '[Software]; path=/media/software; read only = yes; valid users = debbie, fig, alex; admin users = alex'
    ports:
      - target: 137
        published: 137
        mode: host
        protocol: udp
      - target: 138
        published: 138
        mode: host
        protocol: udp
      - target: 139
        published: 139
        mode: host
      - target: 445
        published: 445
        mode: host
    volumes:
      - storage:/media/storage
      -
        type: volume
        source: storage
        target: /media/games
        volume:
          subpath: games
      -
        type: volume
        source: storage
        target: /media/videos
        volume:
          subpath: videos
      -
        type: volume
        source: storage
        target: /media/software
        volume:
          subpath: software
    cap_add:
      - CAP_NET_ADMIN
  simple-file-server:
    image: flaviostutz/simple-file-server
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      -
        type: volume
        source: storage
        target: /data
        volume:
          subpath: shares
    networks:
      - cloudflare
    environment:
      LOCATION_BASE_URL: https://share.taxiera.net
      LOG_LEVEL: debug
