version: '3.7'

networks:
  nginx-proxy:
    external: true

secrets:
  MAIN_RCON_PASS:
    external: true

services:
  1-17:
    image: itzg/minecraft-server
    deploy:
      replicas: 1
    ports:
      - 25569:25565
    environment:
      VERSION: 1.17.1
      MOTD: Vanilla 1.17
      EULA: 'true'
      ENABLE_RCON: 'true'
      restart: always
    volumes:
      - /mnt/md0/minecraft/1.17:/data
  1-18:
    image: itzg/minecraft-server
    deploy:
      replicas: 1
    ports:
      - 25565:25565
      - 25579:25565
      - 8123:8123
    networks:
      - nginx-proxy
    environment:
      TYPE: PAPER
      MEMORY: 4G
      VERSION: 1.18.1
      MOTD: Vanilla 1.18
      EULA: 'true'
      ENABLE_RCON: 'true'
      restart: always
      SYNC_SKIP_NEWER_IN_DESTINATION: 'false'
      COPY_CONFIG_DEST: /data
      VIRTUAL_HOST: map.mc.taxiera.link
      VIRTUAL_PORT: 8123
      LETSENCRYPT_HOST: map.mc.taxiera.link
      LETSENCRYPT_EMAIL: alex.taxiera@gmail.com
    volumes:
      - /mnt/md0/minecraft/1.18:/data
      - ./plugins/1-18:/plugins
      - ./config/1-18:/config
