version: '3.7'

services:
  glizzy-1-20:
    image: itzg/minecraft-server
    ports:
      - target: 25565
        published: 25570
        mode: host
    environment:
      TYPE: PAPER
      MEMORY: 2G
      VERSION: 1.20.2
      MOTD: Vanilla 1.20
      EULA: 'true'
      ENABLE_RCON: 'true'
      RCON_PORT: 28016
      OVERRIDE_SERVER_PROPERTIES: 'true'
      SYNC_SKIP_NEWER_IN_DESTINATION: 'false'
      COPY_CONFIG_DEST: /data
    volumes:
      - /mnt/disk1/minecraft/glizzy-1.20:/data
      - ./plugins/glizzy-1.20:/plugins
      - ./config/glizzy-1.20:/config
  1-20:
    image: itzg/minecraft-server
    ports:
      - target: 25565
        published: 25599
        mode: host
    environment:
      TYPE: PAPER
      MEMORY: 2G
      VERSION: 1.20.2
      MOTD: Vanilla 1.20
      EULA: 'true'
      ENABLE_RCON: 'true'
      RCON_PORT: 28016
      OVERRIDE_SERVER_PROPERTIES: 'true'
      SYNC_SKIP_NEWER_IN_DESTINATION: 'false'
      COPY_CONFIG_DEST: /data
    volumes:
      - /mnt/disk1/minecraft/1.20:/data
      - ./plugins/1-20:/plugins
      - ./config/1-20:/config
  1-19:
    image: itzg/minecraft-server
    ports:
      - target: 25565
        published: 25589
        mode: host
    environment:
      TYPE: PAPER
      MEMORY: 2G
      VERSION: 1.19.3
      MOTD: Vanilla 1.19
      EULA: 'true'
      ENABLE_RCON: 'true'
      RCON_PORT: 28016
      OVERRIDE_SERVER_PROPERTIES: 'true'
      SYNC_SKIP_NEWER_IN_DESTINATION: 'false'
      COPY_CONFIG_DEST: /data
    volumes:
      - /mnt/disk1/minecraft/1.19:/data
      - ./plugins/1-19:/plugins
      - ./config/1-19:/config
  1-18:
    image: itzg/minecraft-server
    ports:
      - target: 25565
        published: 25579
        mode: host
    environment:
      TYPE: PAPER
      MEMORY: 1G
      VERSION: 1.18.1
      MOTD: Vanilla 1.18
      EULA: 'true'
      ENABLE_RCON: 'true'
      RCON_PORT: 28016
      OVERRIDE_SERVER_PROPERTIES: 'true'
      SYNC_SKIP_NEWER_IN_DESTINATION: 'false'
      COPY_CONFIG_DEST: /data
    volumes:
      - /mnt/disk1/minecraft/1.18:/data
      - ./plugins/1-18:/plugins
      - ./config/1-18:/config
  1-17:
    image: itzg/minecraft-server
    ports:
      - target: 25565
        published: 25569
        mode: host
    environment:
      VERSION: 1.17.1
      MOTD: Vanilla 1.17
      EULA: 'true'
      ENABLE_RCON: 'true'
      RCON_PORT: 28016
      OVERRIDE_SERVER_PROPERTIES: 'true'
    volumes:
      - /mnt/disk1/minecraft/1.17:/data