volumes:
  storage:
    external: true 

services:
  main:
    image: vinanrra/7dtd-server
    environment:
      - START_MODE=1 #Change between START MODES
      - VERSION=stable # Change between 7 days to die versions
      - PUID=1000 # Remember to use same as your user
      - PGID=1000 # Remember to use same as your user
      - TimeZone=America/New_York # Optional - Change Timezone
      - TEST_ALERT=NO # Optional - Send a test alert
      - UPDATE_MODS=NO # Optional - This will allow mods to be update on start, each mod also need to have XXXX_UPDATE=YES to update on start
      - ALLOC_FIXES=NO # Optional - Install ALLOC FIXES
      - ALLOC_FIXES_UPDATE # Optional - Update Allocs Fixes before server start
      - UNDEAD_LEGACY=NO # Optional - Install Undead Legacy mod, if DARKNESS_FALLS it's enable will not install anything
      - UNDEAD_LEGACY_VERSION=stable # Optional - Undead Legacy version
      - UNDEAD_LEGACY_UPDATE=NO # Optional - Update Undead Legacy mod before server start
      - DARKNESS_FALLS=NO # Optional - Install Darkness Falls mod, if UNDEAD_LEGACY it's enable will not install anything
      - DARKNESS_FALLS_UPDATE=NO  # Optional - Update Darkness Falls mod before server start
      - DARKNESS_FALLS_URL=False # Optional - Install the provided Darkness Falls url
      - ENZOMBIES=NO # Optional - Install EnZombies mod
      - ENZOMBIES_ADDON_SNUFKIN=NO # Optional - Install EnZombies addon mod
      - ENZOMBIES_ADDON_ROBELOTO=NO # Optional - Install EnZombies addon mod
      - ENZOMBIES_ADDON_NONUDES=NO # Optional - Install EnZombies addon mod
      - ENZOMBIES_UPDATE=NO # Optional - Update EnZombies mod and addons before server start
      - CPM=NO # Optional - CSMM Patron's Mod (CPM)
      - CPM_UPDATE=NO # Optional - Update CPM before server start
      - BACKUP=NO # Optional - Backup server at 5 AM
      - MONITOR=NO # Optional - Keeps server up if crash
    volumes:
      -
        type: volume
        source: storage
        target: /home/sdtdserver/.local/share/7DaysToDie
        volume:
          subpath: 7dtd/main/7DaysToDie
      -
        type: volume
        source: storage
        target: /home/sdtdserver/lgsm/config-lgsm/sdtdserver
        volume:
          subpath: 7dtd/main/LGSM-Config
      -
        type: volume
        source: storage
        target: /home/sdtdserver/serverfiles
        volume:
          subpath: 7dtd/main/ServerFiles
      -
        type: volume
        source: storage
        target: /home/sdtdserver/log
        volume:
          subpath: 7dtd/main/log
      -
        type: volume
        source: storage
        target: /home/sdtdserver/lgsm/backup
        volume:
          subpath: 7dtd/main/backups
    ports:
      - 26900:26900/tcp # Default game ports
      - 26900:26900/udp # Default game ports
      - 26901:26901/udp # Default game ports
      - 26902:26902/udp # Default game ports
      - 8080:8080/tcp # OPTIONAL - WEBADMIN
      - 8081:8081/tcp # OPTIONAL - TELNET
      - 8082:8082/tcp # OPTIONAL - WEBSERVER https://7dtd.illy.bz/wiki/Server%20fixes
    restart: unless-stopped # INFO - NEVER USE WITH START_MODE=4 or START_MODE=0
