version: '3.7'

networks:
  postgres_backend_network:
  nginx-proxy:
    external: true

secrets:
  ADMIN_DB_USER:
    external: true
  ADMIN_DB_PASS:
    external: true
  READONLY_USER:
    external: true
  READONLY_PASS:
    external: true
  NX_CLOUD_DB_NAME:
    external: true
  NX_CLOUD_DB_USER:
    external: true
  NX_CLOUD_DB_PASS:
    external: true
  NX_CLOUD_ADMIN_USER:
    external: true
  NX_CLOUD_ADMIN_PASS:
    external: true
  TRANSMISSION_USER:
    external: true
  TRANSMISSION_PASS:
    external: true
  TRANSMISSION_IP_WHITELIST:
    external: true

services:
  transmission:
    image: ghcr.io/linuxserver/transmission
    deploy:
      replicas: 1
    secrets:
      - TRANSMISSION_USER
      - TRANSMISSION_PASS
      - TRANSMISSION_IP_WHITELIST
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/New_York
      # FILE__USER: /run/secrets/TRANSMISSION_USER
      # FILE__PASS: /run/secrets/TRANSMISSION_PASS
      # HOST_WHITELIST: torrent.taxiera.link
      # VIRTUAL_HOST: torrent.taxiera.link
      # VIRTUAL_PORT: 9091
      # LETSENCRYPT_HOST: torrent.taxiera.link
      # LETSENCRYPT_EMAIL: alex.taxiera@gmail.com
    volumes:
      - /mnt/md0/torrents:/downloads
      - /mnt/md0:/media
      - /home/alex//docker/volumes/transmission/config:/config
      - /home/alex/docker/volumes/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - nginx-proxy

  nextcloud:
    image: nextcloud:24.0.0
    deploy:
      replicas: 1
    depends_on:
      - db
      - nginx-letsencrypt
    networks:
      - postgres_backend_network
      - nginx-proxy
    volumes:
      - /mnt/md0/nextcloud:/var/www/html/data:rw
      -
        type: bind
        source: /home/alex/docker/volumes/nextcloud/data
        target: /var/www/html
    secrets:
      - NX_CLOUD_DB_NAME
      - NX_CLOUD_DB_USER
      - NX_CLOUD_DB_PASS
      - NX_CLOUD_ADMIN_USER
      - NX_CLOUD_ADMIN_PASS
    environment:
      NEXTCLOUD_TRUSTED_DOMAINS: '192.168.11.69 files.taxiera.link'
      POSTGRES_HOST: db
      POSTGRES_DB_FILE: /run/secrets/NX_CLOUD_DB_NAME
      POSTGRES_USER_FILE: /run/secrets/NX_CLOUD_DB_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/NX_CLOUD_DB_PASS
      NEXTCLOUD_ADMIN_USER_FILE: /run/secrets/NX_CLOUD_ADMIN_USER
      NEXTCLOUD_ADMIN_PASSWORD_FILE: /run/secrets/NX_CLOUD_ADMIN_PASS
      VIRTUAL_HOST: files.taxiera.link
      LETSENCRYPT_HOST: files.taxiera.link
      LETSENCRYPT_EMAIL: alex.taxiera@gmail.com

  db:
    image: postgres:13
    deploy:
      replicas: 1
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5555:5432
    networks:
      - postgres_backend_network
    volumes:
      - ./pg/scripts:/docker-entrypoint-initdb.d
      - /var/run/docker.sock:/var/run/docker.sock
      -
        type: bind
        source: /home/alex/docker/volumes/nextcloud/postgres
        target: /var/lib/postgresql/data
    secrets:
      - NX_CLOUD_DB_NAME
      - NX_CLOUD_DB_USER
      - NX_CLOUD_DB_PASS
      - READONLY_USER
      - READONLY_PASS
      -
        source: ADMIN_DB_USER
        target: ADMIN_USER
      -
        source: ADMIN_DB_PASS
        target: ADMIN_PASS
    environment:
      READONLY_ROLE: readonly_role
      POSTGRES_USER_FILE: /run/secrets/ADMIN_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/ADMIN_PASS

  nginx:
    image: nginxproxy/nginx-proxy
    deploy:
      replicas: 1
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - nginx-proxy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/alex/docker/volumes/nextcloud/nginx/conf.d:/etc/nginx/conf.d
      - /home/alex/docker/volumes/nextcloud/nginx/vhost.d:/etc/nginx/vhost.d
      - /home/alex/docker/volumes/nextcloud/nginx/html:/usr/share/nginx/html
      - /home/alex/docker/volumes/nextcloud/nginx/certs:/etc/nginx/certs:ro
      - ./nginx/unlimited_upload.conf:/etc/nginx/conf.d/unlimited_upload.conf:ro

  nginx-letsencrypt:
    image: nginxproxy/acme-companion
    deploy:
      replicas: 1
    depends_on:
      - nginx
    networks:
      - nginx-proxy
    volumes:
      - /home/alex/docker/volumes/nextcloud/nginx/conf.d:/etc/nginx/conf.d
      - /home/alex/docker/volumes/nextcloud/nginx/vhost.d:/etc/nginx/vhost.d
      - /home/alex/docker/volumes/nextcloud/nginx/html:/usr/share/nginx/html
      - /home/alex/docker/volumes/nextcloud/nginx/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/alex/docker/volumes/letsencrypt:/etc/acme.sh
    environment:
      DEFAULT_EMAIL: alex.taxiera@gmail.com
