version: '3.7'

networks:
  nginx-proxy:

services:
  pc-api:
    image: alextaxiera/polished-crystal-api:latest
    deploy:
      replicas: 1
    networks:
      - nginx-proxy
    environment:
      NODE_ENV: production
      VIRTUAL_HOST: pc-api.taxiera.link
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: pc-api.taxiera.link
      LETSENCRYPT_EMAIL: alex.taxiera@gmail.com
    expose:
      - 3000

  nginx:
    image: nginx
    deploy:
      replicas: 1
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/docker/volumes/conf.d:/etc/nginx/conf.d
      - ~/docker/volumes/vhost.d:/etc/nginx/vhost.d
      - ~/docker/volumes/html:/usr/share/nginx/html
      - ~/docker/volumes/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: helder/docker-gen
    deploy:
      replicas: 1
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    command: -notify "docker-label-sighup com.docker.swarm.service.name=web_nginx" -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - nginx-proxy
    volumes:
      - ~/docker/volumes/conf.d:/etc/nginx/conf.d
      - ~/docker/volumes/vhost.d:/etc/nginx/vhost.d
      - ~/docker/volumes/html:/usr/share/nginx/html
      - ~/docker/volumes/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    deploy:
      replicas: 1
    networks:
      - nginx-proxy
    volumes:
      - ~/docker/volumes/conf.d:/etc/nginx/conf.d
      - ~/docker/volumes/vhost.d:/etc/nginx/vhost.d
      - ~/docker/volumes/html:/usr/share/nginx/html
      - ~/docker/volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: alex.taxiera@gmail.com
