version: '3.7'

networks:
  nginx-proxy:

services:
  nginx:
    image: nginx
    deploy:
      replicas: 1
    depends_on:
      - nginx-gen
      - nginx-letsencrypt
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    networks:
      - nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/docker/volumes/conf.d:/etc/nginx/conf.d
      - ~/docker/volumes/vhost.d:/etc/nginx/vhost.d
      - ~/docker/volumes/html:/usr/share/nginx/html
      - ~/docker/volumes/certs:/etc/nginx/certs:ro

  nginx-gen:
    image: jwilder/docker-gen
    deploy:
      replicas: 1
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - nginx-proxy
    volumes:
      - ~/docker/volumes/conf.d:/etc/nginx/conf.d
      - ~/docker/volumes/vhost.d:/etc/nginx/vhost.d
      - ~/docker/volumes/html:/usr/share/nginx/html
      - ~/docker/volumes/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ~/docker/volumes/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    deploy:
      replicas: 1
    networks:
      - nginx-proxy
    volumes:
      - ~/docker/volumes/conf.d:/etc/nginx/conf.d
      - ~/docker/volumes/vhost.d:/etc/nginx/vhost.d
      - ~/docker/volumes/html:/usr/share/nginx/html
      - ~/docker/volumes/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
      NGINX_PROXY_CONTAINER: nginx
